version: 2.1

jobs:
  build-and-test:
    docker:
      - image: fpco/stack-build:lts-17.10
    steps:
      - checkout

      - restore_cache:
          keys:
            - stack-dependencies-{{ arch }}-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}

      - run: stack build --test --bench --only-dependencies

      - save_cache:
          key: stack-dependencies-{{ arch }}-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
          paths:
            - ~/.stack

      - run: stack build --test

workflows:
  version: 2

  build-and-test:
    jobs:
      - build-and-test
