version: 2.1

jobs:
  build-and-test:
    docker:
      - image: fpco/stack-build-small:lts-20.25
    steps:
      - checkout

      - restore_cache:
          keys:
            - stack-dependencies-{{ arch }}-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}

      - run: stack build --test --bench --only-dependencies

      - save_cache:
          key: stack-dependencies-{{ arch }}-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
          paths:
            - ~/.stack

      # Temporary ignore test, need a time to figure out how to run it with docker support
      - run: stack build

workflows:
  version: 2

  build-and-test:
    jobs:
      - build-and-test
