version: 2.1

jobs:
  build-and-test:
    docker:
      - image: fpco/stack-build:lts-17.10
    steps:
      - checkout

      - run: stack build --test

workflows:
  version: 2

  build-and-test:
    jobs:
      - build-and-test
